### ISSUE TITLE
「4.ユースケース」について

### ISSUE THREAD

**Issue by chachamimm** [wot-jp-community/wot-architecture#10]
The Web of Things」の翻訳をどちらにするか決めておいた方がいいと思います。現在の翻訳バージョンだと「モノのウェブ」になっているのですが、それが問題というより、それでも構わないのですが、状況的にこれで一つの名詞となっているので、訳さないで「The Web of Things」か、「Web of Things」かのどちらかにするという考えもあるのではないかと思います。

これは決めの問題だと思います。例えば、この文章のタイトルでも「モノのウェブ(WoT)アーキテクチャ」となっているので、どうしましょうという感じです。

他では、「4.ユースケース」では、である調に変更する程度で問題はないと思います。

**Comment by ashimura** [comment]
PR #13 merged
