### ISSUE TITLE
4.1.4 Utilities

### ISSUE THREAD

**Issue by dshioham** [wot-jp-community/wot-architecture#14]
4.1.4 公益事業

住宅や商工業 (C&I)のメーターの自動読み取りと請求により、資源の消費と潜在的なボトルネックに関する継続的な洞察が得られ**る**。

分散型再生可能エネルギー生成装置の状態と出力を監視することにより、分散型エネルギー資源の最適化が可能に**なる**。

配電設備の監視と遠隔制御は、配電プロセスの自動化に**役立つ**。

発電と配電のインフラストラクチャ（インフラ？）の継続的な監視により、公益事業の現場担当者の安全性を向上**している**。

すいません。訂正提案箇所の示し方が不明で、上記Boldにしたところです。＞１）「である」調に修正、２）「インフラストラクチャ」はインフラで一般化しているという認識の合意があれば、インフラで。公式性を重要視するのであれば、インフラストラクチャのままで。

**Comment by ashimura** [comment]
PR #15 で修正反映ずみ
