### ISSUE TITLE
12行目のエラー

### ISSUE THREAD

**Issue by chachamimm** [wot-jp-community/wot-architecture#159]
Xcodeで見ていると、index.htmlの12行目にエラーがあるのですが、initial;以降の部分がこれでいいのか、確認した方がいいかと思います。

.issue-label {
    text-transform: initial;https://wot-jp-community.github.io/wot-architecture/index.html#changes
  }

**Comment by ashimura** [comment]
[英語原本](https://www.w3.org/TR/2020/REC-wot-architecture-20200409/)を確認しましたが，不要な内容かと思いますので，削除するPRを作成したく思います．

**Comment by ashimura** [comment]
PR #165 available.
