### ISSUE TITLE
4.1.7 工学と建設 (4.1.7 Engineering and Construction)

### ISSUE THREAD

**Issue by matsu200722** [wot-jp-community/wot-architecture#16]
節タイトルを"工学と建設"と訳されていますが、この文脈では、Engineeringは土木工事と訳される方が
適切ではないかと思います。
あと、訳文ではなくて、原文について気になった点を記載します。
"security hazards"と書かれていますが、セキュリティや安全の分野では、security上の危険はrisk、安全上の危険はhazard
という言葉の使い方をすると思います。なので、security hazardという表現には違和感を憶えます。

**Comment by ashimura** [comment]
PR #17で修正ずみ
