### ISSUE TITLE
4.1.11 Smart Cities

### ISSUE THREAD

**Issue by shujikamitsuna** [wot-jp-community/wot-architecture#18]
4.1.11 **スマートシティ**
橋梁、ダム、堤防、運河の資材の状態、劣化、振動**の**監視**により**、保守修理作業を発見し、重大な被害を防**止することができる**。**幹線**道路の監視と適切な標識の提供により、最適な交通の流れが**確保される**。
**スマートパーキングにより**、駐車スペースの利用と可用性**の**最適化**と**追跡**が行われ**、**課金**/予約**が**自動化**される**。
存在検知、天気予報などに基づく街灯のスマート制御により、コストが削減され**る**。
ゴミ容器**の**監視**により**、廃棄物管理**や**ゴミ収集ルートを最適化でき**る**。

- ですます調からである調に修正
- 「スマート・シティ」と「スマート・パーキング」の中点を削除
- 「highway」の訳を「高速道路」から「基幹道路」に修正
- 「billing」の訳を「請求」から「課金」に修正
- その他、日本語として読みやすい表現に修正
- なぜ「Bridges, Dams, Levees, Canals」と頭文字が大文字になっているかは不明
- 「スマートシティ」の修正は、目次も修正（なお、4.1.2.1の「スマートファクトリー」も目次を修正）

**Comment by ashimura** [comment]
PR #19 で修正
