### ISSUE TITLE
4.1.12 Smart Buildings

### ISSUE THREAD

**Issue by k-toumura** [wot-jp-community/wot-architecture#20]
- 節タイトルの"Smart Buildings"の訳語としては、「スマートビルディング」がよく使われているように見えます。中点の必要性に関しては打ち合わせにて議論とさせてください。
- 本文内の"buildings"は「ビル」のままで良いと思われます。
- 他に関しては、である調への変更のみです。

**Comment by ashimura** [comment]
PR #21 で修正ずみ
