### ISSUE TITLE
4.1.13 Connected Car

### ISSUE THREAD

**Issue by otax-h** [wot-jp-community/wot-architecture#22]
## 修正前

4.1.13 コネクテッド・カー
稼働状況の監視、サービス・ニーズの予測により、メンテナンスの必要性とコストが最適化されます。クリティカルな道路・交通状況に関する早期警告システムの通知によりドライバーの安全性が強化されます。

## 修正後

4.1.13 **コネクテッドカー**

稼働状況の監視、**サービスニーズ**の予測により、メンテナンスの必要性とコストが最適化され**る**。クリティカルな道路・交通状況に関する早期警告システムの通知によりドライバーの安全性が強化され**る**。

## 修正点
* タイトルの"コネクテッド・カー"の中点を削除し、より一般的に使われているとみられる"コネクテッドカー"に修正
* 同様に"サービス・ニーズ"の中点削除し、"サービス・ニーズ"に修正
* 文末を"ですます"調から"である"調へ修正

 ## 相談
 * 原文の『Monitoring of operation status, prediction of service needs optimizes maintenance needs and costs.』に対して、『稼働状況の監視、サービスニーズの予測により、メンテナンスの必要性とコストが最適化される。』は訳として正しそうですが、意味が伝わりにくそうです。『optimizes maintenance needs and costs.』は、『適切なコストで適切なメンテナンスがなされる』のようにしては意訳しすぎでしょうか？

**Comment by ashimura** [comment]
PR #30 で修正済み
