### ISSUE TITLE
4.1.9 Healthcare

### ISSUE THREAD

**Issue by chachamimm** [wot-jp-community/wot-architecture#23]
- "new areas"の訳語として、"分野"がいいのか、"領域"がいいのか議論の余地があると思います。私の考えでは"領域"の方がいいのではないかと思います。
- どこまで翻訳するのかという問題があるのですが、"risk"と"critical"をカタカナで"リスク"、"クリティカル"とするのか、”危険"、"致命的な"とするのか、議論の余地があると思います。私の考えでは”危険"、"致命的な"かと思います。
- 他は文章の意味としては問題はないと思いますので、である調への変更だけだと思います。

**Comment by ashimura** [comment]
PR #24 で修正ずみ
