### ISSUE TITLE
4.1.13.1 Connected Car Example

### ISSUE THREAD

**Issue by yamanoi823** [wot-jp-community/wot-architecture#25]
修正前
4.1.13.1　コネクテッド・カーの例
図3は、コネクテッド・カーの例です。このケースでは、ゲートウェイはCANを介して車の部品に接続し、独自のインターフェースを介してカー・ナビゲーション・システムに接続します。クラウドで実行されているサービスは、交通パターンを判断するために、車の部品からプッシュ配信されるデータを収集し、複数の車からのデータを分析します。このケースでは、ゲートウェイはクラウド・サービスを利用して交通データを取得し、カー・ナビゲーション・システムを介してドライバーに表示することもできます。

修正案
4.1.13.1　**コネクテッドカー**の例
図3は、**コネクテッドカー**の例**である**。このケースでは、ゲートウェイはCANを介して車の部品に接続**され**、独自のインターフェースを介して**カーナビゲーションシステム**に接続**される**。クラウドで実行されているサービスは、交通パターンを判断するために、車の部品からプッシュ配信されるデータを収集し、複数の車からのデータを分析**する**。このケースでは、ゲートウェイは**クラウドサービス**を利用して交通データを取得し、**カーナビゲーションシステム**を介してドライバーに表示することも**できる**。

- 「コネクテッド・カー」「カー・ナビゲーション・システム」「クラウド・サービス」の・をとる

- ですます調をである調に。

- 交通パターン？

**Comment by ashimura** [comment]
PR #26 で修正
