### ISSUE TITLE
4.1.2 Industrial

### ISSUE THREAD

**Issue by matsu200722** [wot-jp-community/wot-architecture#8]
・スマート・ファクトリーは、スマートファクトリーという表記の方が一般的ではないかと思います。

・"In this case, field-level, cell and line controllers automate different factory equipment based on industrial communication protocols such as PROFINET, Modbus, OPC UA TSN, EtherCAT, or CAN. "を「このケースでは、現場レベルのセルや回線の制御装置が、PROFINET、Modbus、OPC UA TSN、EtherCAT、CANなどの産業用通信プロトコルに基づいて、別の工場設備をオートメーション化しています。」と訳されているところは、「このケースでは、**現場レベル、セル、工場ライン**の制御装置が、PROFINET、Modbus、OPC UA TSN、EtherCAT、CANなどの産業用通信プロトコルに基づいて、**様々な**工場設備をオートメーション化しています。」と訳された方が良いのではないかと思います。

・"An industrial edge device collects selected data from various controllers and makes it available to a cloud backend service, e.g., for remote monitoring via a dashboard or analyzes it for preventive maintenance."を「産業用のエッジ・デバイスは、様々な制御装置からデータを選択収集して、例えば、ダッシュボードを用いた遠隔監視などのクラウド・バックエンド・サービスでそれを利用できるようにし、予防保全のために分析を行います。」と訳されているところは、「産業用のエッジ・デバイスは、様々な制御装置からデータを選択収集して、例えば、ダッシュボードを用いた遠隔監視などのクラウド・バックエンド・サービスで**データを**利用できるように**したり**、予防保全のために**データの**分析を行います。」と訳された方が良いのではないかと思います。

・サプライ・チェーンは、サプライチェーンという表記の方が一般的ではないかと思います。

**Comment by shujikamitsuna** [comment]
「スマート・ファクトリー」と「サプライ・チェーン」に関しては、それぞれ「スマートファクトリー」と「サプライチェーン」で良いと思います。
基本的に、2つ以上の単語で構成される熟語を訳す際にカタカナの単語が続く場合は、その間に「・」を入れる規則としていますので、他の用語に関しても「・」なしにするかの検討が必要だと思います。

**Comment by shujikamitsuna** [comment]
ポツ2とポツ3の訳の修正案について、異存はありません。

**Comment by matsu200722** [comment]
上綱様、御確認頂き有難うございます。

**Comment by ashimura** [comment]
PR #11 merged
