### ISSUE TITLE
「7. WoT構成要素」の修正案について

### ISSUE THREAD

**Issue by shujikamitsuna** [wot-jp-community/wot-architecture#80]
「7. WoT構成要素」の修正案について、「new branch」を選択するのを忘れて更新してしまいました。大丈夫でしょうか。

**Comment by shujikamitsuna** [comment]
修正部分と説明のURL：
https://github.com/wot-jp-community/wot-architecture/commit/a5248fb26e60ed84ca93d851f31d581fdb937382

**Comment by ashimura** [comment]
普段のPullrequestの代わりに，上記のdiff:
  https://github.com/wot-jp-community/wot-architecture/commit/a5248fb26e60ed84ca93d851f31d581fdb937382
を使って差分を確認いたしましょう :)

**Comment by ashimura** [comment]
12/3の第20回DSTF作業部会で，[修正内容](https://github.com/wot-jp-community/wot-architecture/commit/a5248fb26e60ed84ca93d851f31d581fdb937382)に問題ないことを確認した．
